package com.sep.realvista.domain.user.notification;

public enum EventType {
    NEW_LISTING,
    PRICE_CHANGE,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    NEW_TOUR_REQUEST,
    NEW_MESSAGE,
    LISTING_EXPIRED,
    LISTING_EXPIRING_SOON,
    LISTING_SOLD,
    SYSTEM,
    PROPERTY_3D_GENERATED,
    PROPERTY_3D_FAILED,
    LISTING_RENTED,
    LEASE_TERMINATED,
    NEW_AGENT_PROPOSAL
}
