-- Add APPOINTMENT_RESCHEDULE_PROPOSED, APPOINTMENT_RESCHEDULE_ACCEPTED, and APPOINTMENT_RESCHEDULE_REJECTED to chk_notification_event_type constraint.

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS chk_notification_event_type;

ALTER TABLE notifications ADD CONSTRAINT chk_notification_event_type
    CHECK (event_type IN (
        'NEW_LISTING',
        'PRICE_CHANGE',
        'APPOINTMENT_REMINDER',
        'APPOINTMENT_CONFIRMED',
        'APPOINTMENT_CANCELLED',
        'APPOINTMENT_REJECTED',
        'NEW_TOUR_REQUEST',
        'NEW_MESSAGE',
        'LISTING_EXPIRED',
        'LISTING_EXPIRING_SOON',
        'LISTING_SOLD',
        'SYSTEM',
        'PROPERTY_3D_GENERATED',
        'PROPERTY_3D_FAILED',
        'LISTING_RENTED',
        'LEASE_TERMINATED',
        'NEW_AGENT_PROPOSAL',
        'AGENT_PROPOSAL_ACCEPTED',
        'AGENT_PROPOSAL_REJECTED',
        'OWNER_ENGAGEMENT_REVIEW_REMINDER',
        'LISTING_UNPUBLISHED',
        'PROPERTY_UPDATED_BY_ADMIN',
        'PROPERTY_DELETED_BY_ADMIN',
        'APPOINTMENT_RESCHEDULE_PROPOSED',
        'APPOINTMENT_RESCHEDULE_ACCEPTED',
        'APPOINTMENT_RESCHEDULE_REJECTED'
    ));
