-- Price change notifications for bookmarked listings (in-app + email)
INSERT INTO notification_templates (template_key, name, type, language, title, content_body, created_at, updated_at, deleted)
VALUES
('PRICE_DROP', 'Price Drop on Bookmarked Listing', 'IN_APP', 'vi',
 'Giá đã giảm: {{listingName}}',
 'Bất động sản {{listingName}} bạn đã lưu vừa giảm giá từ {{oldPrice}} xuống {{newPrice}} ({{percent}}%). Xem ngay!',
 NOW(), NOW(), false),
('PRICE_DROP', 'Price Drop on Bookmarked Listing', 'IN_APP', 'en',
 'Price drop: {{listingName}}',
 '{{listingName}} you bookmarked just dropped from {{oldPrice}} to {{newPrice}} ({{percent}}% off).',
 NOW(), NOW(), false),
('PRICE_INCREASE', 'Price Increase on Bookmarked Listing', 'IN_APP', 'vi',
 'Giá đã tăng: {{listingName}}',
 'Bất động sản {{listingName}} bạn đã lưu vừa tăng giá từ {{oldPrice}} lên {{newPrice}} ({{percent}}%).',
 NOW(), NOW(), false),
('PRICE_INCREASE', 'Price Increase on Bookmarked Listing', 'IN_APP', 'en',
 'Price increase: {{listingName}}',
 '{{listingName}} you bookmarked increased from {{oldPrice}} to {{newPrice}} (+{{percent}}%).',
 NOW(), NOW(), false),
('PRICE_DROP_EMAIL', 'Price Drop Email', 'EMAIL', 'vi',
 'Tin vui: {{listingName}} đã giảm giá!',
 'Xin chào,<br/><br/>Bất động sản <b>{{listingName}}</b> bạn đã lưu vừa được cập nhật giá:<br/>- Giá cũ: <s>{{oldPrice}}</s><br/>- Giá mới: <b>{{newPrice}}</b><br/>- Mức giảm: {{diff}} ({{percent}}%)<br/><br/>Xem chi tiết tại RealVista.',
 NOW(), NOW(), false),
('PRICE_DROP_EMAIL', 'Price Drop Email', 'EMAIL', 'en',
 'Good news: {{listingName}} price just dropped!',
 'Hi,<br/><br/><b>{{listingName}}</b> you bookmarked just had a price update:<br/>- Old price: <s>{{oldPrice}}</s><br/>- New price: <b>{{newPrice}}</b><br/>- Saved: {{diff}} ({{percent}}%)<br/><br/>View on RealVista.',
 NOW(), NOW(), false),
('PRICE_INCREASE_EMAIL', 'Price Increase Email', 'EMAIL', 'vi',
 'Cập nhật giá: {{listingName}}',
 'Xin chào,<br/><br/>Bất động sản <b>{{listingName}}</b> bạn đã lưu vừa tăng giá:<br/>- Giá cũ: {{oldPrice}}<br/>- Giá mới: <b>{{newPrice}}</b><br/>- Mức tăng: {{diff}} ({{percent}}%)<br/><br/>Xem chi tiết tại RealVista.',
 NOW(), NOW(), false),
('PRICE_INCREASE_EMAIL', 'Price Increase Email', 'EMAIL', 'en',
 'Price update: {{listingName}}',
 'Hi,<br/><br/><b>{{listingName}}</b> you bookmarked has a new price:<br/>- Old price: {{oldPrice}}<br/>- New price: <b>{{newPrice}}</b><br/>- Increase: {{diff}} ({{percent}}%)<br/><br/>View on RealVista.',
 NOW(), NOW(), false)
ON CONFLICT (template_key, language) DO UPDATE
SET name = EXCLUDED.name,
    title = EXCLUDED.title,
    content_body = EXCLUDED.content_body,
    type = EXCLUDED.type,
    updated_at = NOW();
